# aws lambda function name
aws:
  lambda: 
    crawl_data: "estat-fact-expense-crawl-data-{{ env }}"
    clean_data: "estat-fact-expense-clean-data-{{ env }}"
  s3:
    target_folder: "expense"
snowflake:
  sql:
    load_data_file: "expense/load_expense.sql"
    target_table: "fact_expense_stg"
dbt:
  model: "fact_expense"
data_source:
  stat_url: "https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=1&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&tclass4val=0"