USE SCHEMA ESTAT_DB.ESTAT_MART;

CREATE TABLE IF NOT EXISTS agg_expense_by_main_category (
    KEN_NAME VARCHAR,
    CHIHOU VARCHAR,
    YEAR NUMBER,
    MONTH NUMBER,
    MAIN_CATEGORY_NAME VARCHAR,
    AMOUNT NUMBER,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY VARCHAR,
    UPDATED_BY VARCHAR
);