USE SCHEMA ESTAT_DB.ESTAT_MART;

CREATE TABLE IF NOT EXISTS agg_expense_monthly_total (
    KEN_NAME VARCHAR,
    CHIHOU VARCHAR,
    YEAR NUMBER,
    MONTH NUMBER,
    TOTAL_AMOUNT NUMBER,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY VARCHAR,
    UPDATED_BY VARCHAR
);