USE SCHEMA ESTAT_DB.ESTAT_STG;

CREATE TABLE IF NOT EXISTS dim_expense_category_stg (
    CATEGORY_CD VARCHAR(8),
    MAIN_CATEGORY_NAME VARCHAR,
    SUB_CATEGORY_NAME VARCHAR,
    DETAILED_CATEGORY_NAME VARCHAR,
    DESCRIPTION VARCHAR,
    LOADED_TIME TIMESTAMP,
    LOADED_USER VARCHAR,
    FILENAME VARCHAR
);