USE SCHEMA ESTAT_DB.ESTAT_STG;

CREATE TABLE IF NOT EXISTS dim_expense_catalog_stg (
    CATEGORY_CD VARCHAR(8),
    CATEGORY_NAME VARCHAR,
    MAJOR_CATEGORY_CD VARCHAR(2),
    MEDIUM_CATEGORY_CD VARCHAR(5),
    MAJOR_CATEGORY_NAME VARCHAR,
    MEDIUM_CATEGORY_NAME VARCHAR,
    LOADED_TIME TIMESTAMP,
    LOADED_USER VARCHAR,
    FILENAME VARCHAR
);