USE SCHEMA ESTAT_DB.ESTAT_TRANSFORMED;

CREATE TABLE IF NOT EXISTS dim_location (
    KEN_CODE VARCHAR,
    SITYOUSON_CODE VARCHAR,
    TIIKI_CODE VARCHAR,
    KEN_NAME VARCHAR,
    SITYOUSON_NAME1 VARCHAR,
    SITYOUSON_NAME2 VARCHAR,
    SITYOUSON_NAME3 VARCHAR,
    YOMIGANA VARCHAR,
    CHIHOU VARCHAR,
    CREATED_TIME TIMESTAMP
);
