USE SCHEMA ESTAT_DB.ESTAT_TRANSFORMED;

CREATE TABLE IF NOT EXISTS dim_expense_catalog (
    CATEGORY_CD VARCHAR(8),
    CATEGORY_NAME VARCHAR,
    MAJOR_CATEGORY_CD VARCHAR(2),
    MEDIUM_CATEGORY_CD VARCHAR(5),
    MAJOR_CATEGORY_NAME VARCHAR,
    MEDIUM_CATEGORY_NAME VARCHAR,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP
);