USE SCHEMA ESTAT_DB.ESTAT_TRANSFORMED;

CREATE TABLE IF NOT EXISTS dim_expense_category (
    CATEGORY_CD VARCHAR(8),
    MAIN_CATEGORY_NAME VARCHAR,
    SUB_CATEGORY_NAME VARCHAR,
    DETAILED_CATEGORY_NAME VARCHAR,
    DESCRIPTION VARCHAR,
    CREATED_AT VARCHAR,
    CREATED_BY VARCHAR
);