USE SCHEMA ESTAT_DB.ESTAT_TRANSFORMED;

CREATE TABLE IF NOT EXISTS fact_expense (
    CATEGORY_CD VARCHAR(8),
    AMOUNT DECIMAL, 
    AREA_CD VARCHAR(5), 
    YEAR INT,
    MONTH INT,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY VARCHAR,
    UPDATED_BY VARCHAR
);
