version: 2
models:
  - name: fact_expense
    config:
      materialized: incremental
      unique_key: ['category_cd', 'area_cd', 'year', 'month']
    description: "Transformed table for fact expense"
sources:
  - name: stg
    description: "Staging table"
    database: estat_db
    schema: estat_stg
    tables:
      - name: fact_expense_stg
        description: "Staging table for fact expense"