version: 2
models:
  - name: dim_expense_catalog
    config:
      materialized: table
      unique_key: ['category_cd', 'major_category_cd', 'medium_category_cd']
    description: "Transformed table for list of expense categories"
sources:
  - name: dim_expense_catalog_stg
    database: estat_db
    schema: estat_stg
    tables:
      - name: input_table
        identifier: dim_expense_catalog_stg
        description: "Staging table for dim expense catalog"
  