-- create database and schema and warehouse
USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS ESTAT_DB;
CREATE SCHEMA IF NOT EXISTS ESTAT_STG;
CREATE SCHEMA IF NOT EXISTS ESTAT_TRANSFORMED;
CREATE SCHEMA IF NOT EXISTS ESTAT_MART;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;

-- create role used to transform data in SF
-- give permissions to this role
CREATE ROLE IF NOT EXISTS DEV;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DEV;

GRANT USAGE ON DATABASE ESTAT_DB TO ROLE DEV;
GRANT USAGE, CREATE TABLE ON ALL SCHEMAS IN DATABASE ESTAT_DB TO ROLE DEV;
GRANT USAGE, CREATE TABLE ON FUTURE SCHEMAS IN DATABASE ESTAT_DB TO ROLE DEV;
GRANT ALL ON ALL TABLES IN DATABASE ESTAT_DB TO ROLE DEV;
GRANT ALL ON FUTURE TABLES IN DATABASE ESTAT_DB TO ROLE DEV;
GRANT USAGE ON ALL STAGES IN DATABASE ESTAT_DB TO ROLE DEV;



-- create user for dbt and grant the dev role to dbt
CREATE USER IF NOT EXISTS dbt
  PASSWORD = 'dbt1234'
  LOGIN_NAME = 'dbt'
  DEFAULT_WAREHOUSE = COMPUTE_WH
  DEFAULT_NAMESPACE = ESTAT_DB.ESTAT_STG
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'User for dbt to do transformation tasks on data'
  ;
GRANT ROLE DEV TO USER dbt;


