def dagsChanged = false

pipeline {
    agent any
    environment {
        AIRFLOW_DNS = "ec2-54-168-48-161.ap-northeast-1.compute.amazonaws.com"
    }
    stages {
        stage('Checkout'){
            steps {
                checkout scm
            }
        }
        stage('Check for changes'){
            steps{
                script {
                    def changedFiles = sh(
                        script: "git diff-tree --no-commit-id --name-only -r HEAD",
                        returnStdout: true
                    ).trim()
                    if (!changedFiles.contains('airflow/config') && !changedFiles.contains('airflow/dags')){
                        echo "No changes in airflow dags. Skip task."
                        currentBuild.result = 'SUCCESS'
                        return
                    } else {
                        echo "There are changes in airflow dags, start cloning latest repo to airflow instance.."
                        dagsChanged = true 
                    }
                }
            }
        }
        stage('Clone to Airflow instance if changed'){
            when {
                expression { dagsChanged == true }
            }
            steps {
                sshagent(['jenkins-ec2-key']){
                    sh '''
                    ssh -o StrictHostKeyChecking=no ubuntu@$AIRFLOW_DNS " \
                    project_name='pipeline-estat-dbt-snowflake' && \
                    tmp_folder='pj_latest' && \
                    sudo mkdir -p /tmp/$tmp_folder && \
                    sudo git clone https://github.com/tthuha236/pipeline-estat-dbt-snowflake.git /tmp/$tmp_folder && \
                    cd /opt/$project_name/airflow && \
                    sudo find ./config -type f ! -name "airflow.cfg" -delete && \
                    sudo rsync -av /tmp/$tmp_folder/airflow/config/ ./config/ && \
                    sudo rm -rf ./dags/* && \
                    sudo rsync -av /tmp/$tmp_folder/airflow/dags/ ./dags/ && \
                    sudo rm -rf /tmp/$tmp_folder
                    "
                    '''
                }
            }
        }
    }
}